<script>
  import { goto } from '$app/navigation';

  function navigateToMap() {
    goto('/map');
  }
</script>

<main class="min-h-screen bg-gradient-to-b from-gray-50 to-gray-100 py-16 px-4">
  <div class="max-w-3xl mx-auto">
    <div class="bg-white rounded-2xl shadow-xl p-8 md:p-12">
      <h1 class="text-4xl md:text-5xl font-bold text-gray-800 mb-8 text-center">
        Cluster Visualization Project
      </h1>
      
      <div class="space-y-6 text-gray-600 text-lg mb-12">
        <p>
          Using Mapbox GL JS, this project visualizes clusters generated by the <a href="https://github.com/thomas-cabral/clustopher">clusteropher</a> library.
        </p>
        <p>
          Generate clusters of different densities and sizes to see how they look on a map.
        </p>
      </div>

      <div class="flex justify-center">
        <button 
          on:click={navigateToMap}
          class="group relative inline-flex items-center justify-center px-8 py-4 text-lg font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 transition-colors duration-300 overflow-hidden"
        >
          <span class="relative z-10 flex items-center gap-2">
            Open Map View
            <svg 
              xmlns="http://www.w3.org/2000/svg" 
              class="h-5 w-5 transform group-hover:translate-x-1 transition-transform duration-200" 
              fill="none" 
              viewBox="0 0 24 24" 
              stroke="currentColor"
            >
              <path 
                stroke-linecap="round" 
                stroke-linejoin="round" 
                stroke-width="2" 
                d="M17 8l4 4m0 0l-4 4m4-4H3" 
              />
            </svg>
          </span>
        </button>
      </div>
    </div>

    <div class="mt-8 text-center text-sm text-gray-500">
      <p>
        Generated clusters are saved in the <code>/cluster</code> directory.
      </p>
    </div>
  </div>
</main>

