root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  # Explicitly tell air where to find and run the main files
  cmd = "go build -o ./tmp/runner ./cmd/runners/main.go && go build -o ./tmp/api ./cmd/api/main.go"
  bin = "./tmp/runner & ./tmp/api"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "frontend"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cluster", "cmd", "proto", "runner"]
  include_ext = ["go", "proto"]
  include_file = ["./cmd/runners/main.go", "./cmd/api/main.go"]
  kill_delay = "5s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true